on: [workflow_dispatch] 

name: AzureACI 

jobs:
  createaci: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Login to Azure 
        uses: azure/login@v1 
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
          
      - name: Create ACI 
        uses: azure/CLI@v1 
        with: 
          azcliversion: latest 
          inlineScript: | 
            echo "Create an Azure Container Instance" 
            az container create -g ${{vars.RG_NAME}} --name mycontainerinstance --image timcr01.azurecr.io/nginx:timcopy --registry-password ${{secrets.ACR_PWD}} --registry-username timcr01 --ip-address public --dns-name-label timcr01
